baseURL = "https://bingacademy.github.io/"
languageCode = "en-us"
title = "Bing Academy"
theme = "hugo-serif-theme"

[params]
    google_analytics_id=""

[[menu.main]]
	name = "About"
	url = "/about/"
    weight = 1

[[menu.main]]
    name = "Programs"
    url = "/programs/"
    weight = 2

[[menu.main]]
	name = "Seminars"
	url = "/seminars/"
	weight = 3

[[menu.main]]
	name = "Testimonials"
	url = "/testimonials/"
	weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
